<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Budgeteur.Server.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GenerateProgramFile>false</GenerateProgramFile>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestApp.fs" />
    <Compile Include="TestHttp.fs" />
    <Compile Include="Transactions/EndpointTests.fs" />
    <Compile Include="Transactions/ValidationPropertyTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Budgeteur.Server/Budgeteur.Server.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="Expecto.FsCheck" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>

</Project>
