<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Budgeteur</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ApiError.fs" />
    <Compile Include="DomainError.fs" />
    <Compile Include="RequestLogging.fs" />
    <Compile Include="Coders.fs" />
    <Compile Include="Config.fs" />
    <Compile Include="Auth.fs" />
    <Compile Include="OpenApi.fs" />
    <Compile Include="Json.fs" />
    <Compile Include="Db.fs" />
    <Compile Include="Endpoint.fs" />
    <Compile Include="Money.fs" />
    <!-- Tag Feature Slice -->
    <Compile Include="Tag/Tag.fs" />
    <Compile Include="Tag/Validation.fs" />
    <Compile Include="Tag/Endpoints/Create.fs" />
    <Compile Include="Tag/Endpoints/Read.fs" />
    <Compile Include="Tag/Endpoints/Update.fs" />
    <Compile Include="Tag/Endpoints/Delete.fs" />
    <Compile Include="Tag/Api.fs" />
    <!-- END Tag Feature Slice -->
    <!-- Rule Feature Slice -->
    <Compile Include="Rule/Rule.fs" />
    <Compile Include="Rule/Validation.fs" />
    <Compile Include="Rule/Endpoints/Create.fs" />
    <Compile Include="Rule/Endpoints/Read.fs" />
    <Compile Include="Rule/Endpoints/Update.fs" />
    <Compile Include="Rule/Endpoints/Delete.fs" />
    <Compile Include="Rule/Api.fs" />
    <!-- END Rule Feature Slice -->
    <!-- Transaction Feature Slice -->
    <Compile Include="Transaction/Transaction.fs" />
    <Compile Include="Transaction/Validation.fs" />
    <Compile Include="Transaction/Endpoints/Create.fs" />
    <Compile Include="Transaction/Endpoints/Read.fs" />
    <Compile Include="Transaction/Endpoints/ReadAll.fs" />
    <Compile Include="Transaction/Endpoints/Update.fs" />
    <Compile Include="Transaction/Endpoints/Delete.fs" />
    <Compile Include="Transaction/Api.fs" />
    <!-- END Transaction Feature Slice -->
    <Compile Include="Status.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="migrations/**/*.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FsToolkit.ErrorHandling" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Oxpecker" />
    <PackageReference Include="Oxpecker.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Thoth.Json.Net" />
    <PackageReference Include="dbup-sqlite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SqlHydra.Query" />
  </ItemGroup>

</Project>
