// This code was generated by `SqlHydra.Sqlite` -- v4.0.1.
namespace Budgeteur.Db

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 0, 1)
    let ns = "Budgeteur.Db"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Accounts =
        { Id: System.Guid
          UserId: string
          Number: string
          Name: string
          Balance: decimal
          CurrentAsOf: System.DateTime }

    let Accounts = table<Accounts>

    [<CLIMutable>]
    type Categories =
        { Id: System.Guid
          UserId: string
          Name: string }

    let Categories = table<Categories>

    [<CLIMutable>]
    type HiddenCategories =
        { CategoryId: System.Guid
          UserId: string }

    let HiddenCategories = table<HiddenCategories>

    [<CLIMutable>]
    type Rules =
        { Id: System.Guid
          UserId: string
          Pattern: string
          CategoryId: System.Guid }

    let Rules = table<Rules>

    [<CLIMutable>]
    type SchemaVersions =
        { SchemaVersionID: int64
          ScriptName: string
          Applied: System.DateTime }

    let SchemaVersions = table<SchemaVersions>

    [<CLIMutable>]
    type TaggingQueue =
        { TransactionId: System.Guid
          UserId: string
          CreatedAt: System.DateTime }

    let TaggingQueue = table<TaggingQueue>

    [<CLIMutable>]
    type Transactions =
        { Id: System.Guid
          UserId: string
          Amount: decimal
          Description: string
          Date: System.DateTime
          AccountId: Option<System.Guid>
          ImportHash: Option<string>
          CategoryId: Option<System.Guid> }

    let Transactions = table<Transactions>


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
