// This code was generated by `SqlHydra.Sqlite` -- v5.0.0.
namespace Budgeteur.Data.Db

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(5, 0, 0)
    let ns = "Budgeteur.Data.Db"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module main =

    [<CLIMutable>]
    type Accounts =
        { Id: System.Guid
          UserId: string
          Number: string
          Name: string
          Balance: decimal
          CurrentAsOf: System.DateOnly }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "Id"; Value = box this.Id; ProviderDbType = None }
                  { WriteColumn.Name = "UserId"; Value = box this.UserId; ProviderDbType = None }
                  { WriteColumn.Name = "Number"; Value = box this.Number; ProviderDbType = None }
                  { WriteColumn.Name = "Name"; Value = box this.Name; ProviderDbType = None }
                  { WriteColumn.Name = "Balance"; Value = box this.Balance; ProviderDbType = None }
                  { WriteColumn.Name = "CurrentAsOf"; Value = box this.CurrentAsOf; ProviderDbType = None } ]

    let Accounts = table<Accounts>

    [<CLIMutable>]
    type Rules =
        { Id: System.Guid
          UserId: string
          Pattern: string
          TagId: System.Guid }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "Id"; Value = box this.Id; ProviderDbType = None }
                  { WriteColumn.Name = "UserId"; Value = box this.UserId; ProviderDbType = None }
                  { WriteColumn.Name = "Pattern"; Value = box this.Pattern; ProviderDbType = None }
                  { WriteColumn.Name = "TagId"; Value = box this.TagId; ProviderDbType = None } ]

    let Rules = table<Rules>

    [<CLIMutable>]
    type SchemaVersions =
        { SchemaVersionID: int64
          ScriptName: string
          Applied: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "SchemaVersionID"; Value = box this.SchemaVersionID; ProviderDbType = None }
                  { WriteColumn.Name = "ScriptName"; Value = box this.ScriptName; ProviderDbType = None }
                  { WriteColumn.Name = "Applied"; Value = box this.Applied; ProviderDbType = None } ]

    let SchemaVersions = table<SchemaVersions>

    [<CLIMutable>]
    type TaggingQueue =
        { TransactionId: System.Guid
          UserId: string
          CreatedAt: System.DateTime }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "TransactionId"; Value = box this.TransactionId; ProviderDbType = None }
                  { WriteColumn.Name = "UserId"; Value = box this.UserId; ProviderDbType = None }
                  { WriteColumn.Name = "CreatedAt"; Value = box this.CreatedAt; ProviderDbType = None } ]

    let TaggingQueue = table<TaggingQueue>

    [<CLIMutable>]
    type Tags =
        { Id: System.Guid
          UserId: string
          Name: string
          Color: string }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "Id"; Value = box this.Id; ProviderDbType = None }
                  { WriteColumn.Name = "UserId"; Value = box this.UserId; ProviderDbType = None }
                  { WriteColumn.Name = "Name"; Value = box this.Name; ProviderDbType = None }
                  { WriteColumn.Name = "Color"; Value = box this.Color; ProviderDbType = None } ]

    let Tags = table<Tags>

    [<CLIMutable>]
    type Transactions =
        { Id: System.Guid
          UserId: string
          Amount: decimal
          Description: string
          Date: System.DateOnly
          IsTransfer: bool
          AccountId: Option<System.Guid>
          ImportHash: Option<string>
          TagId: Option<System.Guid> }

        interface IWriteColumns with
            member this.WriteColumns =
                [ { WriteColumn.Name = "Id"; Value = box this.Id; ProviderDbType = None }
                  { WriteColumn.Name = "UserId"; Value = box this.UserId; ProviderDbType = None }
                  { WriteColumn.Name = "Amount"; Value = box this.Amount; ProviderDbType = None }
                  { WriteColumn.Name = "Description"; Value = box this.Description; ProviderDbType = None }
                  { WriteColumn.Name = "Date"; Value = box this.Date; ProviderDbType = None }
                  { WriteColumn.Name = "IsTransfer"; Value = box this.IsTransfer; ProviderDbType = None }
                  { WriteColumn.Name = "AccountId"; Value = box this.AccountId; ProviderDbType = None }
                  { WriteColumn.Name = "ImportHash"; Value = box this.ImportHash; ProviderDbType = None }
                  { WriteColumn.Name = "TagId"; Value = box this.TagId; ProviderDbType = None } ]

    let Transactions = table<Transactions>



type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }
    // This provider holds no factory-level resources; each connection is owned and disposed by its QueryContext.
    member _.Dispose() = ()

    interface System.IDisposable with
        member this.Dispose() = this.Dispose()

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqliteEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.Sqlite.SqliteConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext; OpenContextAsync = openContextAsync }
