<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Budgeteur.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Budgeteur/Budgeteur.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="TestApp.fs" />
    <Compile Include="TestHttp.fs" />
    <Compile Include="Domain/BalanceSheetItemTests.fs" />
    <Compile Include="Domain/BalanceSheetTests.fs" />
    <Compile Include="Data/BalanceSheetItemTests.fs" />
    <Compile Include="Transactions/EndpointTests.fs" />
    <Compile Include="Transactions/TransactionDescriptionPropertyTests.fs" />
    <Compile Include="MoneyTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="Expecto.FsCheck" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
  </ItemGroup>

</Project>
